name: Linters

on: [pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install mypy
        run: |
          python3 -m pip install mypy types-PyYAML types-setuptools
      - name: Add matcher
        run: |
          echo "::add-matcher::.github/workflows/mypy-problem-matcher.json"
      - name: Install package
        run: |
          pip install .
      - name: Run mypy
        run: |
          python3 -m mypy --exclude=build .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install
        run: |
          python3 -m pip install flake8
      - name: Add matcher
        run: |
          echo "::add-matcher::.github/workflows/flake8-problem-matcher.json"
      - name: Lint with flake8
        run: |
          python3 -m flake8 .

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
